### ISSUE TITLE
Pow.Postgres.Store.keys/1 missing 

### ISSUE THREAD

**Issue by Ivor** [ZennerIoT/pow_postgres_store#6]
Hi, thanks for this library. It is very handy. 

Getting this error 
`function Pow.Postgres.Store.keys/1 is undefined or private`

```
    ** (UndefinedFunctionError) function Pow.Postgres.Store.keys/1 is undefined or private
        (pow_postgres_store 1.0.0-rc2) Pow.Postgres.Store.keys([ttl: 1800000, namespace: "credentials"])
        (pow 1.0.18) lib/pow/store/base.ex:185: Pow.Store.Base.binary_key_all/2
        (pow 1.0.18) lib/pow/store/credentials_cache.ex:46: Pow.Store.CredentialsCache.fetch_sessions/3
        (pow 1.0.18) lib/pow/store/credentials_cache.ex:167: Pow.Store.CredentialsCache.do_delete_user_sessions_with_fingerprint/3
        (pow 1.0.18) lib/pow/store/credentials_cache.ex:78: Pow.Store.CredentialsCache.put/3
        (pow 1.0.18) lib/pow/plug/session.ex:192: anonymous fn/6 in Pow.Plug.Session.before_send_create/3
        (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (plug 1.8.3) lib/plug/conn.ex:1555: Plug.Conn.run_before_send/2
        (plug 1.8.3) lib/plug/conn.ex:404: Plug.Conn.send_resp/1
        (pow_assent 0.4.6) lib/pow_assent/phoenix/controllers/authorization_controller.ex:1: PowAssent.Phoenix.AuthorizationController.action/2
        (pow_assent 0.4.6) lib/pow_assent/phoenix/controllers/authorization_controller.ex:1: PowAssent.Phoenix.AuthorizationController.phoenix_controller_pipeline/2
```

I have verified that the latest RC does not seem to have the `keys/1` function.

**Comment by narrowtux** [comment]
Which version of pow are you using?

**Comment by Ivor** [comment]
I was using pow 1.0.18 (from the stacktrace above). 
I have upgraded to Pow 1.0.20 which still has the keys function, as can be seen here: https://github.com/danschultzer/pow/blob/e0d52658cbdf800f42acca8461047d4730db39bd/lib/pow/store/backend/mnesia_cache.ex - it also implements the same function in the ets_cache.ex.

I haven't seen this error again, and I am not sure what caused it. 
This is used in combination with Assent and Pow. Perhaps a unique edge case. I am going ahead with the implementation as is, since I haven't experienced the problem again.

**Comment by narrowtux** [comment]
I think this error ocurred intermittently between versions and now there's a default implementation in the newer pow version.

**Comment by Ivor** [comment]
I think that is the case. I haven't seen anything happen again. I don't know how to reproduce it at this point so for now I believe it is fixed. Sorry for the bother, thanks for the great work. It is making my life much better.
