### ISSUE TITLE
Compilation warning: variable "errors" is unused

### ISSUE THREAD

**Issue by DavidOliver** [ZennerIoT/pow_postgres_store#7]
Having updated to Elixir 1.11, I'm on a mission to work through compilation warnings and noticed this one for pow_postgres_store.

It's already [been fixed](https://github.com/ZennerIoT/pow_postgres_store/commit/4c15ca8059580357261e1d2b76b9afce54cf3a89) but needs a hex package release: https://hex.pm/packages/pow_postgres_store

(Is 'narrowtux', the owner of the hex package, you?)

Thanks!

**Comment by pehbehbeh** [comment]
I would also be interested in this. Is this package actively maintained? @narrowtux

**Comment by narrowtux** [comment]
Sorry, I just missed the PR.

**Comment by narrowtux** [comment]
I just released v1.0 🎉

**Comment by pehbehbeh** [comment]
Great! Thank you. 👍
